### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by raorsa** [Laravel-Backpack/activity-log#46]
the translations identifier

'backpack.activity-log::activity_log.causer_model'

not show value

but change this line to

'backpack::activity_log.causer_model'

He show correct value

**Comment by karandatwani92** [comment]
Hey @raorsa  Thanks for reporting the issue.

@pxpm What do you think on this:

Our old packages use the following string identifier syntax:

```
trans('backpack::base.welcome'),✅
trans('backpack::crud.add'),✅
trans('backpack::logmanager.delete_confirm'),✅
trans('backpack::pagemanager.meta_title'),✅
trans('backpack::backup.unknown_disk'),✅
```

But for newer packages, it it going odd!
```
trans('backpack.activity-log::activity_log.causer_model'),❌
trans('backpack.calendaroperation::calendaroperation.update_success'),❌
trans("backpack.translation-manager::translation_manager.revert"),❌
```

**Comment by karandatwani92** [comment]
For that reason, `backpack.activity-log::` is good to go with. 👍 Thanks

Also, I doubt the possibility of avoiding the use of the package name twice? `backpack.activity-log::activity-log.*`
That's why we end up with.. what it is...

Or is there a possibility to think of something like `backpack.activity-log::translations.*`? 
Otherwise, we can close the issue. Thanks for giving the clarity.

**Comment by pxpm** [comment]
One thing is the namespace `backpack.activity-log::`, the other is the name of the file where the translations are located, in this case `activity_log.php`. We could change the file name to `translations` and use `backpack.activity-log::translations.*` but I don't think it's worth the breaking change at this point. 

Cheers
