### ISSUE TITLE
[Feature Request] Support for Backpack v6.x

### ISSUE THREAD

**Issue by quiquegarcia** [Laravel-Backpack/activity-log#7]
# Feature Request

### What I am trying to achieve

Upgrade to Backpack V6

### What I've already tried to fix it

Simply upgrading guide, but got some version conflicts.

### Would I be able to work on this myself and submit a PR

Yes, but wil take me some time.

**Comment by tabacitu** [comment]
Wow, I didn't know anybody is using this - I thought this is still closed-source 😅

We will add v6 support to this, yes. In fact I think @phpfour will take a look at this in a few weeks because we need it ourselves. But I can't promise anything @quiquegarcia . If you need this on v6, please try doing `composer require backpack/activity-log:"dev-v6"` which will pull the branch this PR uses: https://github.com/Laravel-Backpack/activity-log/pull/8 . That should eliminate the composer errors you're seeing. But tbh I haven't tested it AT ALL, so please tell me if anything else needs fixing, or submit PRs for them.

Appologies for the sloppy PR, but this is low on our priority list at the moment, since it's this package isn't officially released yet. We'll take a closer look in the next few weeks, but right now we're bogged down in some big issues in the main packages which occupy all our teams' time.

Closing the issue itself - let's move the conversation to the PR please 🙏
Cheers!
